spring:
  application:
    name: product-gateway
  main:
    banner-mode: off

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

gateway:
  security:
    login: false
    customer: false
    product: false
    order: false
    payment: false
    paymentHistory: false
    inventory: false
    notification: false
    employee: false
    enabled: true