spring:
  application:
    name: product-gateway
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

gateway:
  security:
    login: false
    user: true
    product: true
    order: true
    payment: true
    paymentHistory: true
    inventory: true
    notification: true
    employee: true
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      payment-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s